#
#    __                          __
#   / /____ ___ ____  ___  ___ _/ /       This file is provided to you by https://github.com/tegonal/github-commons
#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        Copyright 2022 Tegonal Genossenschaft <info@tegonal.com>
#  \__/\__/\_, /\___/_//_/\_,_/_/         It is licensed under Creative Commons Zero v1.0 Universal
#         /___/                           Please report bugs and contribute back your improvements
#
#                                         Version: v5.0.2
###################################
name: Cleanup

on:
  push:
    branches:
      - main
      - develop
#gt-placeholder-trigger-end

#gt-placeholder-permissions.v2-start
permissions:
  contents: read
  pull-requests: write
#gt-placeholder-permissions.v2-end

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.12.10
          ln -s website_example ./django/website
      - name: Cleanup code
        run: ./scripts/cleanup-on-push-to-main.sh
      - name: Create Pull Request if necessary
        uses: peter-evans/create-pull-request@v7
        with:
          branch: auto-cleanup
          title: Auto Cleanup
          commit-message: auto cleanup sources
          body: Looks like someone forgot to run ./scripts/cleanup-on-push-to-main.sh before committing. I did it for them :)
          delete-branch: true
          token: ${{ secrets.AUTO_PR_TOKEN }}
          push-to-fork: ${{ vars.AUTO_PR_FORK_NAME != '' && vars.AUTO_PR_FORK_NAME || secrets.AUTO_PR_FORK_NAME }}
